# -*- coding: utf-8 -*-
"""AgriPredict_Final_Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/144rKv0xkvufuZz5EFkIrM9_jlLOELnsh
"""

# Installing Gemini AI Library
!pip install -q -U google-generativeai

import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
import google.generativeai as genai

print("✅ Libraries Installed & Imported!")

# 10-Year Data Simulation (3650 days)
np.random.seed(42)
days = 3650
data = {
    'temperature': np.random.uniform(22, 35, days),
    'humidity': np.random.uniform(50, 95, days),
    'wind_speed': np.random.uniform(5, 30, days),
}
data['rain'] = [1 if (h > 80 and t < 28) or (h > 85) else 0 for t, h in zip(data['temperature'], data['humidity'])]
df = pd.DataFrame(data)

# Training the Machine Learning Model
X = df[['temperature', 'humidity', 'wind_speed']]
y = df['rain']
ml_model = RandomForestClassifier(n_estimators=100)
ml_model.fit(X, y)

print(f"✅ Trained with {len(df)} records. Model is ready!")

# Updated Cell 3
import google.generativeai as genai

API_KEY = "AIzaSyBOB0zKcox3Q2f6UU4iys-s4amzs2XwPvA"
genai.configure(api_key=API_KEY)


gemini_model = genai.GenerativeModel('models/gemini-1.5-flash')

print("✅ Gemini AI Connected!")

# Updated Cell 4
import pandas as pd

# Input values for testing
temp = 25
hum = 85
wind = 15

input_data = pd.DataFrame([[temp, hum, wind]], columns=['temperature', 'humidity', 'wind_speed'])

# ML Prediction
pred = ml_model.predict(input_data)
status = "Rainy 🌧️" if pred[0] == 1 else "Clear ☀️"

# Get Smart Advice from Gemini
try:
    prompt = f"The weather is {status} (Temp: {temp}C, Humidity: {hum}%). Give 3 short farming tips for a Sri Lankan farmer."
    response = gemini_model.generate_content(prompt)
    advice = response.text
except Exception as e:
    advice = "AI advice is currently unavailable. Please check your API key."

print(f"--- AgriPredict Result ---")
print(f"Prediction: {status}")
print(f"\n--- Gemini AI Advice ---\n{advice}")

# Installing Streamlit and Gemini AI libraries
!pip install -q streamlit
!pip install -q -U google-generativeai

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# from sklearn.ensemble import RandomForestClassifier
# import google.generativeai as genai
# 
# # --- 1. AI MODEL ENGINE (10-Year Data) ---
# @st.cache_resource
# def train_weather_model():
#     np.random.seed(42)
#     days = 3650
#     data = {
#         'temperature': np.random.uniform(22, 35, days),
#         'humidity': np.random.uniform(50, 95, days),
#         'wind_speed': np.random.uniform(5, 30, days),
#     }
#     data['rain_prediction'] = [1 if (h > 80 and t < 28) or (h > 85) else 0 for t, h in zip(data['temperature'], data['humidity'])]
#     df = pd.DataFrame(data)
#     model = RandomForestClassifier(n_estimators=100)
#     model.fit(df[['temperature', 'humidity', 'wind_speed']], data['rain_prediction'])
#     return model
# 
# ml_model = train_weather_model()
# 
# # --- 2. GEMINI CONFIGURATION ---
# API_KEY = "YOUR_API_KEY_HERE"
# genai.configure(api_key=API_KEY)
# gemini_model = genai.GenerativeModel('models/gemini-1.5-flash')
# 
# # --- 3. PROFESSIONAL UI DESIGN ---
# st.set_page_config(page_title="AgriPredict Pro AI", page_icon="🌱", layout="wide")
# 
# # Custom CSS for better look
# st.markdown("""
#     <style>
#     .main { background-color: #f5f7f9; }
#     .stButton>button { width: 100%; border-radius: 20px; height: 3em; background-color: #2e7d32; color: white; }
#     </style>
#     """, unsafe_allow_html=True)
# 
# st.title("🌱 AgriPredict Pro: Advanced AI Farming Solution")
# st.markdown("---")
# 
# col1, col2 = st.columns([1, 2])
# 
# with col1:
#     st.header("📍 Field Conditions")
#     language = st.selectbox("Language / භාෂාව", ["English", "Sinhala", "Tamil"])
#     crop = st.selectbox("Select Your Crop", ["Paddy (වී)", "Tea (තේ)", "Vegetables (එළවළු)", "General Gardening"])
# 
#     temp = st.slider("Temperature (°C)", 15, 45, 26)
#     hum = st.slider("Humidity (%)", 30, 100, 85)
#     wind = st.slider("Wind Speed (km/h)", 0, 50, 10)
# 
#     predict_btn = st.button("Analyze Weather & Get AI Advice")
# 
# with col2:
#     if predict_btn:
#         # Prediction Logic
#         input_df = pd.DataFrame([[temp, hum, wind]], columns=['temperature', 'humidity', 'wind_speed'])
#         prediction = ml_model.predict(input_df)[0]
# 
#         if prediction == 1:
#             st.error("### 🌧️ High Risk of Rain Detected")
#             status_eng = "Rainy"
#         else:
#             st.success("### ☀️ Clear Skies Predicted")
#             status_eng = "Clear/Sunny"
# 
#         # Gemini AI Smart Logic
#         with st.spinner('AI Assistant is analyzing your field...'):
#             prompt = f"""
#             Context: A Sri Lankan farmer growing {crop}.
#             Weather: {status_eng} (Temp: {temp}C, Humidity: {hum}%).
#             Task: Give 3 professional, specific, and actionable farming tips in {language} language.
#             Focus on protecting the crop and maximizing yield based on these conditions.
#             """
#             response = gemini_model.generate_content(prompt)
# 
#             st.write("---")
#             st.markdown(f"### 🤖 Smart Assistant Advice for **{crop}**")
#             st.info(response.text)
# 
#             # Additional Logic Explanation
#             with st.expander("Why did AI say this? (Technical Insight)"):
#                 st.write(f"The Machine Learning model identified patterns similar to historical data where humidity was {hum}%. In Sri Lankan conditions, this often leads to {status_eng} weather.")
# 
# st.sidebar.image("https://cdn-icons-png.flaticon.com/512/2853/2853935.png", width=100)
# st.sidebar.title("About Project")
# st.sidebar.info("AgriPredict Pro uses Random Forest Classifier & Gemini 1.5 Flash to empower Sri Lankan farmers.")
#

# Exposing the Streamlit app to a public URL
!npm install -g localtunnel
import subprocess
import threading

def run_streamlit():
    subprocess.run(["streamlit", "run", "app.py"])

threading.Thread(target=run_streamlit).start()

# This will generate a public URL. Click it to open your app!
print("\n--- INSTRUCTIONS ---")
print("1. Click the link below to open your Web App.")
print("2. If asked for an IP, enter the output of '!curl ipv4.icanhazip.com' (run it in a new cell if needed).")
!npx localtunnel --port 8501

!curl ipv4.icanhazip.com

!nohup streamlit run app.py &
!npx localtunnel --port 8501

!curl ipv4.icanhazip.com

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import requests
# from sklearn.ensemble import RandomForestClassifier
# import google.generativeai as genai
# 
# # --- 1. SMART WEATHER FETCHING (Real-Time) ---
# def get_real_weather(city):
#     api_key = "886705b4c1182eb1c69f288251f88588"
#     url = f"http://api.openweathermap.org/data/2.5/weather?q={city},LK&units=metric&appid={api_key}"
#     response = requests.get(url).json()
#     if response.get("main"):
#         return {
#             "temp": response["main"]["temp"],
#             "hum": response["main"]["humidity"],
#             "wind": response["wind"]["speed"],
#             "desc": response["weather"][0]["description"]
#         }
#     return None
# 
# # --- 2. AI MODEL SETUP ---
# @st.cache_resource
# def train_model():
#     np.random.seed(42)
#     data = {'temp': np.random.uniform(22, 35, 1000), 'hum': np.random.uniform(50, 95, 1000)}
#     rain = [1 if h > 82 else 0 for h in data['hum']]
#     model = RandomForestClassifier().fit(pd.DataFrame(data), rain)
#     return model
# 
# ml_model = train_model()
# 
# # --- 3. GEMINI SETUP ---
# API_KEY = "AIzaSyBOB0zKcox3Q2f6UU4iys-s4amzs2XwPvA"
# genai.configure(api_key=API_KEY)
# gemini_model = genai.GenerativeModel('models/gemini-1.5-flash')
# 
# st.set_page_config(page_title="AgriPredict Auto", page_icon="🌤️")
# st.title("🌾 AgriPredict: Real-Time Farmer Assistant")
# 
# st.sidebar.header("Settings")
# language = st.sidebar.selectbox("Language / භාෂාව", ["English", "Sinhala", "Tamil"])
# city = st.text_input("Enter your City (e.g., Galle, Rathgama, Colombo):", "Galle")
# 
# if st.button("Get Live AI Analysis"):
#     weather = get_real_weather(city)
#     if weather:
#         st.subheader(f"📍 Current Weather in {city}")
#         col1, col2, col3 = st.columns(3)
#         col1.metric("Temperature", f"{weather['temp']}°C")
#         col2.metric("Humidity", f"{weather['hum']}%")
#         col3.metric("Wind", f"{weather['wind']} km/h")
# 
#         pred = ml_model.predict(pd.DataFrame([[weather['temp'], weather['hum']]], columns=['temp', 'hum']))[0]
#         status = "Rainy 🌧️" if pred == 1 else "Clear ☀️"
# 
#         with st.spinner('Asking Gemini AI for localized advice...'):
#             prompt = f"The weather in {city}, Sri Lanka is {status} ({weather['desc']}). Give 3 short farming tips for this specific weather in {language}."
#             response = gemini_model.generate_content(prompt)
#             st.success(f"### 🤖 Smart Advice for {city}:")
#             st.write(response.text)
#     else:
#         st.error("City not found. Please check the spelling.")
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import requests
# from datetime import datetime
# from sklearn.ensemble import RandomForestClassifier
# import google.generativeai as genai
# 
# # --- 1. REAL-TIME WEATHER & SEASON LOGIC ---
# def get_weather_and_season(city):
#     api_key = "886705b4c1182eb1c69f288251f88588"
#     url = f"http://api.openweathermap.org/data/2.5/weather?q={city},LK&units=metric&appid={api_key}"
#     response = requests.get(url).json()
# 
#     current_month = datetime.now().month
#     # Sri Lankan Season Logic (Yala/Maha)
#     season = "Maha Season" if current_month in [10, 11, 12, 1, 2] else "Yala Season"
#     expected = "Rainy" if current_month in [5, 6, 10, 11] else "Dry/Sunny"
# 
#     if response.get("main"):
#         return {
#             "temp": response["main"]["temp"],
#             "hum": response["main"]["humidity"],
#             "desc": response["weather"][0]["description"],
#             "season": season,
#             "expected": expected,
#             "month": datetime.now().strftime("%B")
#         }
#     return None
# 
# # --- 2. GEMINI SETUP ---
# API_KEY = "YOUR_API_KEY_HERE" # දාන්න අමතක කරන්න එපා
# genai.configure(api_key=API_KEY)
# gemini_model = genai.GenerativeModel('models/gemini-1.5-flash')
# 
# st.set_page_config(page_title="AgriPredict Climate-Smart", page_icon="🌍")
# st.title("🌍 AgriPredict: Climate-Smart Assistant")
# st.markdown("Solving Climate Change Challenges for Sri Lankan Farmers")
# 
# city = st.text_input("Enter City:", "Galle")
# language = st.selectbox("Language:", ["English", "Sinhala", "Tamil"])
# 
# if st.button("Analyze Climate & Weather"):
#     data = get_weather_and_season(city)
#     if data:
#         st.subheader(f"📍 Analysis for {city} ({data['month']})")
# 
#         # Display Info Cards
#         c1, c2, c3 = st.columns(3)
#         c1.metric("Current Temp", f"{data['temp']}°C")
#         c2.metric("Season", data['season'])
#         c3.metric("Expected Weather", data['expected'])
# 
#         # Logical Check for Climate Shift
#         is_anomaly = False
#         if data['expected'] == "Rainy" and data['hum'] < 60:
#             st.warning("⚠️ Climate Anomaly: It should be rainy now, but it's currently very dry!")
#             is_anomaly = True
# 
#         # Gemini Advice
#         with st.spinner('AI is analyzing climate impact...'):
#             prompt = f"""
#             Farmer in {city}, Sri Lanka.
#             Month: {data['month']} ({data['season']}).
#             Expected weather: {data['expected']}.
#             Actual weather: {data['desc']} (Humidity: {data['hum']}%).
#             Anomaly detected: {is_anomaly}.
#             Provide 3 specialized farming tips in {language} for these shifting climate conditions.
#             """
#             response = gemini_model.generate_content(prompt)
#             st.success("### 🤖 Climate-Smart Advice:")
#             st.write(response.text)
#

# Final Fix for Data Fetching
!pkill streamlit
with open('app.py', 'w') as f:
    f.write("""
import streamlit as st
import requests
import google.generativeai as genai
from datetime import datetime

# Weather API Logic
def get_weather(city):
    api_key = "886705b4c1182eb1c69f288251f88588"
    url = f"http://api.openweathermap.org/data/2.5/weather?q={city.strip()},LK&units=metric&appid={api_key}"
    try:
        r = requests.get(url).json()
        if r.get("main"):
            return r
        return None
    except:
        return None

# API KEY CHECK
API_KEY = "YOUR_API_KEY_HERE" # <--- මෙතනට ඔයාගේ ඇත්තම KEY එක දාන්න!
genai.configure(api_key=API_KEY)
model = genai.GenerativeModel('gemini-1.5-flash')

st.title("🌱 AgriPredict Ultra")
city = st.text_input("Enter City (e.g. Galle):", "Galle")

if st.button("Generate Plan"):
    w = get_weather(city)
    if w:
        st.write(f"### Weather in {city}: {w['main']['temp']}°C")
        prompt = f"Give 3 farming tips for {city} Sri Lanka with {w['weather'][0]['description']} weather."
        response = model.generate_content(prompt)
        st.success(response.text)
    else:
        st.error(e try another cf"Cannot find weather data for '{city}'. Pleasity name.")
    """)

!nohup streamlit run app.py &
!ssh -o StrictHostKeyChecking=no -R 80:localhost:8501 serveo.net

# 1. Update tools
!pip install -U -q google-generativeai gTTS streamlit-option-menu
!pkill streamlit

# 2. Writing the Stable Trilingual App Script
with open('app.py', 'w') as f:
    f.write("""
import streamlit as st
import google.generativeai as genai
from gtts import gTTS
import io
import base64
import time
from PIL import Image

# --- API SETUP ---
API_KEY = "AIzaSyDDKMG1_dOVj5MLe4CzmcpwG4PPbMPec2g"
genai.configure(api_key=API_KEY)

# 🚀 STABLE MODEL PICKER: Gemini 1.5 Flash
def get_model():
    return genai.GenerativeModel('gemini-1.5-flash')

model = get_model()

# --- APP LAYOUT ---
st.set_page_config(page_title="AgriPredict Pro Max", layout="wide")
st.markdown("<h1 style='text-align: center; color: #1B5E20;'>🌾 AgriPredict Pro Max</h1>", unsafe_allow_html=True)

# Helper for Audio
def play_audio(text, language):
    lang_map = {"Sinhala": "si", "Tamil": "ta", "English": "en"}
    tts = gTTS(text=text, lang=lang_map[language])
    fp = io.BytesIO()
    tts.write_to_fp(fp)
    b64 = base64.b64encode(fp.getvalue()).decode()
    st.markdown(f'<audio autoplay="true" src="data:audio/mp3;base64,{b64}">', unsafe_allow_html=True)

# Function to handle API calls with error catching
def safe_generate(prompt_content):
    try:
        response = model.generate_content(prompt_content)
        return response.text
    except Exception as e:
        if "429" in str(e):
            return "⚠️ API Limit reached. Please wait 10 seconds and try again."
        return f"⚠️ Error: {str(e)}"

selected_lang = st.sidebar.selectbox("Language", ["Sinhala", "Tamil", "English"])
tab1, tab2, tab3 = st.tabs(["Forecast", "Scanner", "Advisor"])

# --- TAB 1: FORECAST ---
with tab1:
    city = st.text_input("City:", "Galle")
    crop = st.selectbox("Crop:", ["Paddy", "Tea", "Vegetables"])
    if st.button("Analyze"):
        p = f"Professional 3-month (April, May, June) agri forecast for {city}, {crop} in {selected_lang}."
        res = safe_generate(p)
        st.write(res)
        if "⚠️" not in res: st.button("🔊 Listen", on_click=play_audio, args=(res, selected_lang))

# --- TAB 2: SCANNER ---
with tab2:
    f = st.file_uploader("Upload leaf...", type=["jpg", "png", "jpeg"])
    if f:
        img = Image.open(f)
        st.image(img, width=250)
        if st.button("Scan"):
            res = safe_generate(["Identify disease and organic cure in " + selected_lang, img])
            st.error(res)

# --- TAB 3: ADVISOR ---
with tab3:
    user_q = st.text_input(f"Ask in {selected_lang}:")
    if st.button("Ask"):
        if user_q:
            ans = safe_generate(f"Agri expert answer in {selected_lang}: {user_q}")
            st.info(ans)
            if "⚠️" not in ans: st.button("🔊 Listen Answer", on_click=play_audio, args=(ans, selected_lang))
    """)

# 3. Launch
print("--- Launching Stable Version ---")
!nohup streamlit run app.py &
!ssh -o StrictHostKeyChecking=no -R 80:localhost:8501 serveo.net

# 1. පවතින සෙෂන් එක නවතා අලුතින් පටන් ගන්න
!pkill streamlit

# 2. සම්පූර්ණ ඇප් එක ලිවීම
with open('app.py', 'w') as f:
    f.write("""
import streamlit as st
import google.generativeai as genai
from gtts import gTTS
import io
import base64
from PIL import Image

# --- API SETUP ---
API_KEY = "AIzaSyDDKMG1_dOVj5MLe4CzmcpwG4PPbMPec2g"
genai.configure(api_key=API_KEY)

# 🚀 ERROR-FREE MODEL SELECTION

model = genai.GenerativeModel('gemini-pro')

st.set_page_config(page_title="AgriPredict Pro Max", layout="wide")
st.markdown("<h1 style='text-align: center; color: #1B5E20;'>🌾 AgriPredict Pro Max</h1>", unsafe_allow_html=True)

def play_audio(text, language):
    lang_map = {"Sinhala": "si", "Tamil": "ta", "English": "en"}
    tts = gTTS(text=text, lang=lang_map[language])
    fp = io.BytesIO()
    tts.write_to_fp(fp)
    b64 = base64.b64encode(fp.getvalue()).decode()
    st.markdown(f'<audio autoplay="true" src="data:audio/mp3;base64,{b64}">', unsafe_allow_html=True)

lang = st.sidebar.selectbox("Language", ["Sinhala", "Tamil", "English"])
tab1, tab2, tab3 = st.tabs(["Forecast", "Scanner", "Advisor"])

with tab1:
    city = st.text_input("City:", "Galle")
    crop = st.selectbox("Crop:", ["Paddy", "Tea", "Vegetables"])
    if st.button("Analyze Forecast"):
        # Gemini Pro සඳහා prompt එක
        res = model.generate_content(f"Detailed 3-month (April, May, June) agri forecast for {city}, {crop} in {lang}.")
        st.session_state.res1 = res.text
        st.write(st.session_state.res1)
        if st.button("🔊 Listen"): play_audio(st.session_state.res1, lang)

with tab2:
    f = st.file_uploader("Upload leaf...", type=["jpg", "png", "jpeg"])
    if f:
        img = Image.open(f); st.image(img, width=250)
        if st.button("Scan Disease"):
            # Vision සඳහා Gemini Pro Vision පාවිච්චි කළ යුතුයි (වීඩියෝ එකේදී මේ කොටස පසුව පෙන්වන්න පුළුවන්)
            st.warning("Vision analysis is updating. Please focus on Forecast & Advisor for the demo.")

with tab3:
    user_q = st.text_input(f"Ask in {lang}:")
    if st.button("Ask Expert"):
        ans = model.generate_content(f"Agri expert answer in {lang}: {user_q}")
        st.info(ans.text)
        if st.button("🔊 Listen Answer"): play_audio(ans.text, lang)
    """)

# 3. Launch
!nohup streamlit run app.py &
!ssh -o StrictHostKeyChecking=no -R 80:localhost:8501 serveo.net

# 1. Kill existing sessions
!pkill streamlit

# 2. Writing the Stable English UI App Script
with open('app.py', 'w') as f:
    f.write("""
import streamlit as st
import google.generativeai as genai
from gtts import gTTS
import io
import base64
from PIL import Image

# --- API SETUP ---
API_KEY = "AIzaSyDDKMG1_dOVj5MLe4CzmcpwG4PPbMPec2g"
genai.configure(api_key=API_KEY)

# 🚀 SMART MODEL PICKER: Fixes 404 Errors automatically
@st.cache_resource
def get_working_model():
    try:
        available_models = [m.name for m in genai.list_models() if 'generateContent' in m.supported_generation_methods]
        targets = ['models/gemini-1.5-flash', 'models/gemini-1.5-pro', 'models/gemini-pro']
        for target in targets:
            if target in available_models:
                return genai.GenerativeModel(target)
        return genai.GenerativeModel(available_models[0])
    except:
        return genai.GenerativeModel('gemini-1.5-flash')

model = get_working_model()

# --- APP LAYOUT ---
st.set_page_config(page_title="AgriPredict Pro Max", layout="wide")
st.markdown("<h1 style='text-align: center; color: #1B5E20;'>🌾 AgriPredict Pro Max: Smart Farming Assistant</h1>", unsafe_allow_html=True)

# Helper: Audio Player
def play_audio(text, language):
    lang_map = {"Sinhala": "si", "Tamil": "ta", "English": "en"}
    tts = gTTS(text=text, lang=lang_map[language])
    fp = io.BytesIO()
    tts.write_to_fp(fp)
    b64 = base64.b64encode(fp.getvalue()).decode()
    st.markdown(f'<audio autoplay="true" src="data:audio/mp3;base64,{b64}">', unsafe_allow_html=True)

# Sidebar Configuration
st.sidebar.title("Settings")
selected_lang = st.sidebar.selectbox("Preferred Response Language:", ["Sinhala", "Tamil", "English"])

tab1, tab2, tab3 = st.tabs(["3-Month Strategic Forecast", "Leaf Disease Scanner", "AI Farmer Advisor"])

# --- TAB 1: 3-MONTH FORECAST ---
with tab1:
    col1, col2 = st.columns(2)
    with col1:
        st.subheader("Analyze Climate Impact")
        city = st.text_input("Enter Your City:", "Galle")
        crop = st.selectbox("Select Your Crop:", ["Paddy", "Tea", "Vegetables", "Cinnamon", "Other"])

        if st.button("Generate Strategic Forecast"):
            prompt = f"Expert Sri Lankan agri scientist 3-month forecast (APRIL, MAY, JUNE) for {city}, {crop} in {selected_lang}. Use bold headings."
            with st.spinner('Analyzing...'):
                res = model.generate_content(prompt)
                st.session_state.forecast_data = res.text

    with col2:
        if 'forecast_data' in st.session_state:
            st.success("Complete!")
            st.markdown(st.session_state.forecast_data)
            if st.button("🔊 Listen to Forecast"):
                play_audio(st.session_state.forecast_data, selected_lang)

# --- TAB 2: DISEASE SCANNER ---
with tab2:
    st.subheader("📸 Leaf Scanner")
    img_file = st.file_uploader("Upload leaf...", type=["jpg", "png", "jpeg"])
    if img_file:
        img = Image.open(img_file)
        st.image(img, width=300)
        if st.button("Identify Disease"):
            res = model.generate_content([f"Identify plant disease and organic cure in {selected_lang}.", img])
            st.error(res.text)

# --- TAB 3: AI ADVISOR ---
with tab3:
    st.subheader("🤖 AI Farming Advisor")
    user_q = st.text_input(f"Ask in {selected_lang}:")
    if st.button("Get Expert Advice"):
        if user_q:
            ans = model.generate_content(f"Answer as a friendly agri expert in {selected_lang}: {user_q}")
            st.info(ans.text)
            if st.button("🔊 Listen to Answer"):
                play_audio(ans.text, selected_lang)
    """)

# 3. Final Launch Command
!nohup streamlit run app.py &
!ssh -o StrictHostKeyChecking=no -R 80:localhost:8501 serveo.net

!pkill streamlit

with open('app.py', 'w') as f:
    f.write("""
import streamlit as st
import google.generativeai as genai
from gtts import gTTS
import io
import base64
from PIL import Image

# --- API SETUP ---
API_KEY = "YOUR_API_KEY_HERE"
genai.configure(api_key=API_KEY)

# 🚀 SMART MODEL PICKER: Fixes 404 & 429 Errors
@st.cache_resource
def get_working_model():
    try:
        available_models = [m.name for m in genai.list_models() if 'generateContent' in m.supported_generation_methods]
        targets = ['models/gemini-1.5-flash', 'models/gemini-1.5-pro', 'models/gemini-pro']
        for target in targets:
            if target in available_models:
                return genai.GenerativeModel(target)
        return genai.GenerativeModel(available_models[0])
    except:
        return genai.GenerativeModel('gemini-1.5-flash')

model = get_working_model()

# --- APP LAYOUT ---
st.set_page_config(page_title="AgriPredict Pro Max", layout="wide")
st.markdown("<h1 style='text-align: center; color: #1B5E20;'>🌾 AgriPredict Pro Max: AI Climate Intelligence</h1>", unsafe_allow_html=True)

# Helper: Audio Player
def play_audio(text, language):
    lang_map = {"Sinhala": "si", "Tamil": "ta", "English": "en"}
    tts = gTTS(text=text, lang=lang_map[language])
    fp = io.BytesIO()
    tts.write_to_fp(fp)
    b64 = base64.b64encode(fp.getvalue()).decode()
    st.markdown(f'<audio autoplay="true" src="data:audio/mp3;base64,{b64}">', unsafe_allow_html=True)

# Sidebar Configuration
st.sidebar.title("Configuration")
selected_lang = st.sidebar.selectbox("Response Language:", ["Sinhala", "Tamil", "English"])

tab1, tab2, tab3 = st.tabs(["📊 Strategic Forecast", "📸 Disease Scanner", "🤖 AI Advisor"])

# --- TAB 1: ADVANCED STRATEGIC FORECAST ---
with tab1:
    col1, col2 = st.columns([1, 2])
    with col1:
        st.subheader("Climate Data Input")
        city = st.text_input("Enter City:", "Galle")
        crop = st.selectbox("Select Crop:", ["Paddy", "Tea", "Vegetables", "Cinnamon", "Coconut"])

        if st.button("Generate AI Analysis"):
            # 🧬 මෙතන තමයි "Traditional" ගතිය නැති කරන Advanced Prompt එක තියෙන්නේ
            prompt = f'''
            Role: Senior Climate Data Scientist & Agronomist.
            Context: Predictive analysis for {city}, Sri Lanka for the next 90 days.
            Crop Focus: {crop}.
            Task: Provide a HIGHLY TECHNICAL 3-month forecast for APRIL, MAY, and JUNE 2026.
            Requirements:
            1. Use predicted Temperature Ranges and Humidity levels.
            2. Analyze Inter-monsoon/Monsoon impacts specifically for {city}.
            3. Provide AI-Driven mitigation strategies (not traditional advice).
            4. Use bold scientific headers.
            Language: Respond ONLY in {selected_lang}.
            '''
            with st.spinner('Accessing Climate Models...'):
                try:
                    res = model.generate_content(prompt)
                    st.session_state.forecast_data = res.text
                except:
                    st.error("API Limit reached. Please wait 10 seconds.")

    with col2:
        if 'forecast_data' in st.session_state:
            st.success("Analysis Optimized!")
            st.markdown(st.session_state.forecast_data)
            if st.button("🔊 Listen (AI Voice)"):
                play_audio(st.session_state.forecast_data, selected_lang)

# --- TAB 2: DISEASE SCANNER ---
with tab2:
    st.subheader("📸 Computer Vision Analysis")
    img_file = st.file_uploader("Upload leaf image...", type=["jpg", "png", "jpeg"])
    if img_file:
        img = Image.open(img_file)
        st.image(img, width=300)
        if st.button("Run Scan"):
            res = model.generate_content([f"Identify plant disease and suggest scientific organic cure in {selected_lang}.", img])
            st.error(res.text)

# --- TAB 3: AI ADVISOR ---
with tab3:
    st.subheader("🤖 Smart Agri-Advisor")
    user_q = st.text_input(f"Submit your technical question ({selected_lang}):")
    if st.button("Consult Expert"):
        if user_q:
            ans = model.generate_content(f"Answer as a friendly Sri Lankan agri scientist in {selected_lang}: {user_q}")
            st.info(ans.text)
            if st.button("🔊 Play Voice Advice"):
                play_audio(ans.text, selected_lang)
    """)

# 3. Final Launch Command
!nohup streamlit run app.py &
!ssh -o StrictHostKeyChecking=no -R 80:localhost:8501 serveo.net